name: 'Release AVADO Package'
description: 'Releases the AVADO package with GitHub actions when the PR is merged on master/main'
inputs:
  token:
    description: 'Github token'
    default: ${{ github.token }}
  rpcToken:
    description: 'RPC Auth token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
