name: 'Release AVADO Package'
inputs:
  token:
    description: 'Github token'
    default: ${{ github.token }}
  rpcToken:
    description: 'RPC Auth token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
